return {
    Eggs = {
        "113 | Tech Ciruit Egg",
        "114 | Tech City Egg",
        "115 | Tech Forest Egg",
        "116 | Tech Silo Egg",
        "117 | Tech Data Egg",
        "118 | Tech Cuboid Egg",
        "119 | Tech Sprout Egg",
        "120 | Tech Tree Egg",
        "121 | Tech Incubator Egg",
        "122 | Tech Overgrown Egg",
        "123 | Tech Magma Egg",
        "124 | Tech Oasis Egg",
        "125 | Tech Palm Egg",
        "126 | Tech Coral Egg",
        "127 | Tech Ship Egg",
        "128 | Tech Ruins Egg",
        "129 | Tech Dusty Egg",
        "130 | Tech Luminati Egg",
        "131 | Tech Cactus Egg",
        "132 | Tech Cowboy Egg",
        "133 | Tech Canyon Egg",
        "134 | Tech Snow Egg",
        "135 | Tech Mossy Egg",
        "136 | Tech Ice Crystal Egg",
        "137 | Tech Flurry Egg",
        "138 | Tech Ice Circuit Egg",
        "139 | Tech Glacier Egg",
        "140 | Tech Melted Egg Egg",
        "141 | Tech Nexus Egg",
        "142 | Nuclear Crack Egg",
        "143 | Nuclear Forest Egg",
        "144 | Nuclear Mine Egg",
        "145 | Nuclear Egg",
        "146 | Tech Rocket Egg",
        "147 | Tech Planets Egg",
        "148 | Tech Moon Egg",
        "149 | Tech Mars Egg",
        "150 | Tech Saturn Egg",
        "151 | Tech Comet Egg",
        "152 | Tech Galaxy Egg",
        "153 | Electric Garden Egg",
        "154 | Electric City Egg",
        "155 | Electric Forest Egg",
        "156 | Electric Egg",
        "157 | Tech Factory Egg",
        "158 | Tech Robot Egg",
        "159 | Tech Hive Egg",
        "160 | Alien Garden Egg",
        "161 | Alien Forest Egg",
        "162 | Alien Lab Egg",
        "163 | Alien UFO Egg",
        "164 | Space Forge Egg",
        "165 | Space Factory Egg",
        "166 | Space Junkyard Egg",
        "167 | Steampunk Gears Egg",
        "168 | Steampunk Lantern Egg",
        "169 | Steampunk Clockwork Egg",
        "170 | Steampunk Airship Egg",
        "171 | Motherboard Egg",
        "172 | Aura Egg",
        "173 | Wizard Ruins Egg",
        "174 | Wizard Temple Egg",
        "175 | Wizard Forest Egg",
        "176 | Wizard Tower Egg",
        "177 | Wizard Dungeon Egg",
        "178 | Cyberpunk Undercity Egg",
        "179 | Cyberpunk Industrial Egg",
        "180 | Cyberpunk City Egg",
        "181 | Cyberpunk Road Egg",
        "182 | Tech Kyoto Egg",
        "183 | Tech Samurai Egg",
        "184 | Tech Dojo Egg",
        "185 | Tech Sakura Egg",
        "186 | Dominus Rex Egg",
        "187 | Dominus Frigidus Egg",
        "188 | Dominus Infernus Egg",
        "189 | Holographic Pipes Egg",
        "190 | Holographic Egg",
        "191 | Holographic Tree Egg",
        "192 | Holographic Crystal Egg",
        "193 | Dark Tech Stone Egg",
        "194 | Dark Tech Relic Egg",
        "195 | Dark Tech Castle Egg",
        "196 | Dark Tech Brick Egg",
        "197 | Dark Tech Spike Egg",
        "198 | Hacker Metal Egg",
        "199 | Hacker Gear Egg",
        "200 | Hacker Matrix Egg",
        "201 | Hacker Error Egg",
        "202 | Glitch Tree Egg",
        "203 | Glitch Green Egg",
        "204 | Glitch Aqua Egg",
        "205 | Glitch Cyan Egg",
        "206 | Quantum Egg",
        "207 | Quantum Leafy Egg",
        "208 | Quantum Space Egg",
        "209 | Quantum Galaxy Egg",
        "210 | Void Crystal Egg",
        "211 | Void Fracture Egg",
        "212 | Void Spiral Egg"
    }
}
